bytes_discord_client:
    client_id: '%env(DISCORD_CLIENT_ID)%'
    client_secret: '%env(DISCORD_CLIENT_SECRET)%'
    bot_token: '%env(DISCORD_BOT_TOKEN)%'
    client_public_key: '%env(DISCORD_PUBLIC_KEY)%'